apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"frontend","env":"prod"},"name":"frontend","namespace":"prod"},"spec":{"loadBalancerIP":"34.58.192.5","ports":[{"port":80,"targetPort":80}],"selector":{"app":"frontend","env":"prod"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-05-20T00:13:06Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: frontend
    env: prod
  name: frontend
  namespace: prod
  resourceVersion: "1747770210133375021"
  uid: bb7f3cb0-a623-4f18-b33e-aafd52b29c33
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.228.91
  clusterIPs:
  - 34.118.228.91
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 34.58.192.5
  ports:
  - nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
    env: prod
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.58.192.5
      ipMode: VIP
