apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: app-k8s
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-k8s
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-k8s
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
