name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'release/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: forca-app-459118
      LOCATION: us-central1
      REPOSITORY: forca-repo
      IMAGE_NAME: us-central1-docker.pkg.dev/forca-app-459118/forca-repo/forcaapi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./forca.api
        run: npm install

      - name: Run tests
        working-directory: ./forca.api
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Determine namespace
        id: ns
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "NAMESPACE=stage" >> $GITHUB_ENV
          else
            echo "NAMESPACE=prod" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$TAG ./forca.api
          docker push $IMAGE_NAME:$TAG
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ secrets.GKE_CLUSTER }}'
          location: '${{ secrets.GKE_ZONE }}'

      - name: Update backend image on GKE
        run: |
          TAG=${GITHUB_SHA::7}
          kubectl set image deployment/backend backend=$IMAGE_NAME:$TAG -n $NAMESPACE
          kubectl rollout status deployment/backend -n $NAMESPACE
        env:
          GITHUB_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          NAMESPACE: ${{ env.NAMESPACE }}

      - name: Notify Slack on PR
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🔁 *${{ github.event.pull_request.user.login }}* abriu um Pull Request: *${{ github.event.pull_request.title }}* \n🔗 <${{ github.event.pull_request.html_url }}|Ver PR>"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack (release only)
        if: startsWith(github.ref, 'refs/tags/release/')
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":rocket: Nova versão *${{ github.ref_name }}* do backend foi publicada em *pré-produção*!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
