#pipelinee
name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'release/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jeanmendonca/forcaapi:latest
      K8S_NAMESPACE: ${{ github.ref_name == 'dev' && secrets.K8S_NAMESPACE_STAGE || secrets.K8S_NAMESPACE_PROD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./forca.api
        run: npm install

      - name: Run tests
        working-directory: ./forca.api
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME ./forca.api
          docker push $IMAGE_NAME

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ secrets.GKE_CLUSTER }}'
          location: '${{ secrets.GKE_ZONE }}'

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/${{ env.K8S_NAMESPACE }}/
